services:
  slfractals:
    image: slfractals:latest
    build:
      dockerfile: Dockerfile
      context: .
      target: application
    ports:
      - ${BOKEH_PORT:-5006}:${BOKEH_PORT:-5006}
    environment:
      - ALLOW_PORT=${BOKEH_PORT:-5006}
    container_name: slfractals-app

  notebook:
    image: slfractals:environment
    build:
      dockerfile: Dockerfile
      context: .
      target: environment
    command: jupyter server --no-browser --allow-root --ip 0.0.0.0 --ServerApp.token ${JUPYTER_PW:-mandelbr0t} --port ${JUPYTER_PORT:-8888}
    ports:
      - ${JUPYTER_PORT:-8888}:${JUPYTER_PORT:-8888}
    volumes:
      - ${LOCAL_WS:-.}:/slfractals
    environment:
      - PYTHONPATH=/slfractals/src
    container_name: slfractals-notebook
